version: "2"
run:
  concurrency: 8
  go: "1.24.1"
  build-tags:
    - integration
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gomoddirectives
    - gosec
    - govet
    - inamedparam
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - (io.Closer).Close
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G307
    govet:
      disable:
        - fieldalignment
      enable-all: true
    nakedret:
      max-func-lines: 1
    revive:
      confidence: 0.8
      severity: warning
    staticcheck:
      checks:
        - -ST1000
        - -ST1003
        - all
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - bodyclose
          - errcheck
          - gosec
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: github.com/yusupovanton/golib
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/yusupovanton/golib
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
